// GENERATED by scripts/gen-seed-index.mts. Do not edit by hand.
// 30 public-domain seed recipes, statically bundled.

import type { RecipeDoc } from "./types.ts";

import s0 from "../../../seed/recipes/2-step-chicken-1b8cc666.json";
import s1 from "../../../seed/recipes/apple-coffee-cake-8023052b.json";
import s2 from "../../../seed/recipes/apple-wedges-with-pumpkin-almond-butter-60d5f50d.json";
import s3 from "../../../seed/recipes/avocado-black-bean-taquitos-21c8855e.json";
import s4 from "../../../seed/recipes/baked-fish-6a712530.json";
import s5 from "../../../seed/recipes/baked-trout-0781d2fc.json";
import s6 from "../../../seed/recipes/barley-jambalaya-fae1f18b.json";
import s7 from "../../../seed/recipes/beef-and-vegetable-soup-cfeeae02.json";
import s8 from "../../../seed/recipes/bell-pepper-nachos-793101a1.json";
import s9 from "../../../seed/recipes/black-eyed-pea-and-collard-greens-soup-20aaec24.json";
import s10 from "../../../seed/recipes/bread-pudding-with-vanilla-sauce-cea096b4.json";
import s11 from "../../../seed/recipes/bronco-beans-c8c8db64.json";
import s12 from "../../../seed/recipes/butternut-squash-pasta-bake-dca1565a.json";
import s13 from "../../../seed/recipes/carrots-with-tomatoes-and-macaroni-10111978.json";
import s14 from "../../../seed/recipes/chicken-and-dumplings-00725c42.json";
import s15 from "../../../seed/recipes/chicken-rice-and-fruit-salad-f6a1e60d.json";
import s16 from "../../../seed/recipes/chickpea-dip-ba42ff42.json";
import s17 from "../../../seed/recipes/cinnamon-raisin-breakfast-mix-e2fe0059.json";
import s18 from "../../../seed/recipes/confetti-grain-salad-e2b5447d.json";
import s19 from "../../../seed/recipes/corn-toasties-b3a15895.json";
import s20 from "../../../seed/recipes/creamy-chicken-hash-ca47ccd3.json";
import s21 from "../../../seed/recipes/crusty-rice-with-tofu-and-vegetables-eb6f1a92.json";
import s22 from "../../../seed/recipes/curried-squash-stew-56ebb88e.json";
import s23 from "../../../seed/recipes/dutch-apple-yogurt-dessert-fc136568.json";
import s24 from "../../../seed/recipes/eggs-over-kale-and-sweet-potato-grits-741ff2bd.json";
import s25 from "../../../seed/recipes/fat-free-apple-crumb-dessert-27b4016f.json";
import s26 from "../../../seed/recipes/food-group-funny-face-88c638fc.json";
import s27 from "../../../seed/recipes/frozen-pear-pops-3887bc79.json";
import s28 from "../../../seed/recipes/fruit-salad-30e512be.json";
import s29 from "../../../seed/recipes/garden-barley-soup-3642cd8b.json";

export interface SeedEntry {
  doc: RecipeDoc;
  seed: { fetchUrl: string; attributionUrl: string; license: string };
  meta: { canonicalHash?: string };
}

export const seedRecipes: SeedEntry[] = [
  s0 as unknown as SeedEntry,
  s1 as unknown as SeedEntry,
  s2 as unknown as SeedEntry,
  s3 as unknown as SeedEntry,
  s4 as unknown as SeedEntry,
  s5 as unknown as SeedEntry,
  s6 as unknown as SeedEntry,
  s7 as unknown as SeedEntry,
  s8 as unknown as SeedEntry,
  s9 as unknown as SeedEntry,
  s10 as unknown as SeedEntry,
  s11 as unknown as SeedEntry,
  s12 as unknown as SeedEntry,
  s13 as unknown as SeedEntry,
  s14 as unknown as SeedEntry,
  s15 as unknown as SeedEntry,
  s16 as unknown as SeedEntry,
  s17 as unknown as SeedEntry,
  s18 as unknown as SeedEntry,
  s19 as unknown as SeedEntry,
  s20 as unknown as SeedEntry,
  s21 as unknown as SeedEntry,
  s22 as unknown as SeedEntry,
  s23 as unknown as SeedEntry,
  s24 as unknown as SeedEntry,
  s25 as unknown as SeedEntry,
  s26 as unknown as SeedEntry,
  s27 as unknown as SeedEntry,
  s28 as unknown as SeedEntry,
  s29 as unknown as SeedEntry,
];
