// Generate src/lib/recipe/seed-data.ts with static imports of every seed
// recipe JSON. Static imports bundle at build time, so the interim seed store
// works in Node dev and on Cloudflare Workers alike (no runtime fs). Rerun
// after seed-import changes the pack. Usage: node scripts/gen-seed-index.mts

import { readFileSync, readdirSync, writeFileSync } from "node:fs";

const dir = new URL("../seed/recipes/", import.meta.url);
const files = readdirSync(dir)
  .filter((f) => f.endsWith(".json"))
  .sort();
if (files.length === 0) throw new Error("no seed recipes; run seed-import first");

const slugs = new Set<string>();
for (const file of files) {
  const { doc } = JSON.parse(readFileSync(new URL(file, dir), "utf8")) as { doc: { slug: string } };
  if (slugs.has(doc.slug)) throw new Error(`duplicate slug ${doc.slug}; resolve before generating`);
  slugs.add(doc.slug);
}

const imports = files.map((f, i) => `import s${i} from "../../../seed/recipes/${f}";`).join("\n");
const list = files.map((_, i) => `  s${i} as unknown as SeedEntry,`).join("\n");

const out = `// GENERATED by scripts/gen-seed-index.mts. Do not edit by hand.
// ${files.length} public-domain seed recipes, statically bundled.

import type { RecipeDoc } from "./types.ts";

${imports}

export interface SeedEntry {
  doc: RecipeDoc;
  seed: { fetchUrl: string; attributionUrl: string; license: string };
  meta: { canonicalHash?: string };
}

export const seedRecipes: SeedEntry[] = [
${list}
];
`;

writeFileSync(new URL("../src/lib/recipe/seed-data.ts", import.meta.url), out);
console.log(`wrote src/lib/recipe/seed-data.ts with ${files.length} entries`);
