// Turn seed/recipes/*.json into one idempotent SQL file for the recipes
// table. Dedupe hashes are computed from the attribution URL so a future user
// pasting the original link hits the cache. Run after seed-import:
//   node scripts/seed-to-sql.mts   -> writes seed/seed-insert.sql

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { canonicalizeUrl, canonicalUrlHash } from "../src/lib/recipe/canonical.ts";
import type { RecipeDoc } from "../src/lib/recipe/types.ts";

interface SeedFile {
  doc: RecipeDoc;
  seed: { fetchUrl: string; attributionUrl: string; license: string };
}

const dir = new URL("../seed/recipes/", import.meta.url);
const files = readdirSync(dir).filter((f) => f.endsWith(".json"));
if (files.length === 0) throw new Error("no seed recipes; run seed-import first");

function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const rows: string[] = [];
for (const file of files) {
  const { doc, seed } = JSON.parse(readFileSync(new URL(file, dir), "utf8")) as SeedFile;
  const canonical = canonicalizeUrl(seed.attributionUrl);
  const hash = await canonicalUrlHash(canonical.canonicalUrl);
  const payload = { ...doc, seedLicense: seed.license };
  rows.push(
    `(${sqlString(hash)}, ${sqlString(canonical.canonicalUrl)}, 'article', ${sqlString(
      doc.source?.platform ?? "myplate.gov",
    )}, ${sqlString(doc.source?.creatorHandle ?? "USDA MyPlate Kitchen")}, ${sqlString(doc.slug)}, ${sqlString(
      doc.dish,
    )}, ${sqlString(JSON.stringify(payload))}::jsonb, true, false)`,
  );
}

const sql = `-- Generated by scripts/seed-to-sql.mts from ${files.length} public-domain seed recipes.
-- Idempotent: conflicts on canonical_url_hash are skipped.
insert into public.recipes
  (canonical_url_hash, source_url, source_type, source_platform, creator_handle, slug, dish_name, recipe_json, is_public, is_inferred)
values
${rows.join(",\n")}
on conflict (canonical_url_hash) do nothing;
`;

writeFileSync(new URL("../seed/seed-insert.sql", import.meta.url), sql);
console.log(`wrote seed/seed-insert.sql with ${rows.length} recipes`);
